"""
Central configuration: every file path used by the pipeline lives here.

Override any location with an environment variable instead of editing code:
    TEM_DATA_DIR   folder with the field data      (default: ./data)
    LIBTEM1D       compiled Fortran shared library (default: ./fortran/libtem1d.so)
    TEM_WORK_DIR   where outputs are written       (default: ./outputs)
"""
import os
from pathlib import Path

ROOT     = Path(__file__).resolve().parent
DATA_DIR = Path(os.environ.get("TEM_DATA_DIR", ROOT / "data"))
WORK_DIR = Path(os.environ.get("TEM_WORK_DIR", ROOT / "outputs"))
LIB_PATH = Path(os.environ.get("LIBTEM1D",     ROOT / "fortran" / "libtem1d.so"))

# ---- field data (NOT shipped in this repository; see data/README.md) ----
USF_PATH = DATA_DIR / "June data.usf"   # 40 soundings, LM + HM gates (Lonar Lake survey)
XYZ_PATH = DATA_DIR / "Line001.xyz"     # Aarhus SPIA smooth-inversion export, 40 stations x 20 layers
LM40_CSV = DATA_DIR / "LM40.csv"        # optional: single-sounding LM curve for the forward-model demo
HM40_CSV = DATA_DIR / "HM40.csv"        # optional: single-sounding HM curve for the forward-model demo

# ---- generated by the pipeline (written to WORK_DIR) ----
TRAIN_NPZ = WORK_DIR / "tem1d_train.npz"   # step 01 -> step 02
CNF_DIR   = WORK_DIR / "nn_cnf_1"                              # step 02 -> steps 03, 04

WORK_DIR.mkdir(parents=True, exist_ok=True)
